server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG

security:
  oauth2:
    server:
      url: http://localhost:8080
    resource:
      tokenInfoUri: http://localhost:8080/oauth/check_token
      #filter-order: 3
      preferTokenInfo: true

    client:
      accessTokenUri: http://localhost:8080/oauth/token
      userAuthorizationUri: http://localhost:8080/oauth/authorize
      authorityUri: http://localhost:8080/
      clientAuthenticationScheme: form
      clientId: 10086
      clientSecret: 123456
      provider: support
      grantType: password
    sso: 
      login-path: /login

#开发配置
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/support?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8
        username: root
        password: admin
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa: 
        show-sql: true
        hibernate: 
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    
mybatis:
    typeAliasesPackage: com.hanshow.support.server.model
    mapperLocations: classpath:com.hanshow.support.server.mapper/*.xml
    config-location: classpath:mybatis-config.xml
http:
  allowed: 
    origin: true
        